spring:
  redis:
    host: 192.168.109.121
    port: 6379
    password: 202011
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.109.121:3306/cloud_oauth?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: SHINIANhou:2020
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: 192.168.109.121
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  mvc:
    servlet:
      load-on-startup: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
# 自定义的配置项
access_token:
  store-jwt: false
  jwt-signing-key: xiao@wei@jia@gou=$==+_+%0%:)(:)
  add-userinfo: false
logging:
  level:
    root: debug
    com.cloud: debug
  file: logs/${spring.application.name}.log
# 启动即加载用户中心的ip端口号等信息
ribbon:
  eager-load:
    enabled: true
    clients: user-center
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000